apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: afzaalahmedkhan/vprofileapp
          ports:
            - name: vproapp-port
              containerPort: 8080
     # initContainers:
      #  - name: afzaal-init-first-db
       #   image: busybox:latest
        #  command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
        #- name: afzaal-init-first-cache
         # image: busybox:latest
          #command: ['sh', '-c', 'until nslookup vpromemcached; do echo waiting for mc; sleep 2; done;']
          

          